### ISSUE TITLE
recipes bug version

### ISSUE THREAD

**Issue by Oscarinelx** [BenWoodworth/FastCraft#156]
## Description
when I have certain objects in my inventory I cannot create

## Reproduction
- birch_log (all kinds of wood log) --> does not manufacture= birch_planks,oak_planks,ect...

- birch_planks (planks of all kinds) --> does not manufacture= stick,bowl,white_bed,red_bed (all kinds of bed colors)
![image](https://fotos.subefotos.com/445b4c63967f48bb09d5902eaa885098o.png)

- suspicius_stew ---> can be created with a single bowl
![image](https://fotos.subefotos.com/6162a6174b2732dbe6e31d1f54afe118o.png)

## Server Details
- FastCraft Version: FastCraft v3.0.0-beta.4
- Server Version: spigot 1.14.4

**Comment by BenWoodworth** [comment]
Could you try this?
[FastCraft.jar](https://652-53271895-gh.circle-artifacts.com/0/artifacts/FastCraft.jar)

For suspicious_stew (and some other "complex" recipes), Bukkit gives incorrect recipes, so FastCraft can't craft them properly. To fix that, I just fixed them so they don't show up in FastCraft.

**Comment by Oscarinelx** [comment]
ok, the missing objects already appeared.
-suspicious_stew still appears with 1 bowl.
-the plugin works fine,but when i start the server this message appears:
[15:29:49] [Server thread/ERROR]: Could not load 'plugins\FastLoginCore.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:138) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by BenWoodworth** [comment]
I played around with it some more, and I think this should fix it:
[FastCraft.jar](https://658-53271895-gh.circle-artifacts.com/0/artifacts/FastCraft.jar)

**Comment by Oscarinelx** [comment]
Perfect already works well :D

**Comment by BenWoodworth** [comment]
Alright, awesome!! Thanks for reporting it :)
